# -------------------------------------------------
# Basic Site Information
# -------------------------------------------------
name:               "Waves Lab"
title:              "Waves Lab at the University of Pennsylvania"
description:        "The Kording Lab is a computational neuroscience and causality research group at the University of Pennsylvania."


# -------------------------------------------------
# URL Settings
# -------------------------------------------------
url:                https://penn-waves-lab.github.io
baseurl:


# -------------------------------------------------
# Permalink Settings
# -------------------------------------------------
permalink:          /:year/:month/:day/:title.html  # URL structure for blog posts (default with date)


# -------------------------------------------------
# Collections
# -------------------------------------------------
collections:
  people:
    output:         true  # This ensures each person's profile will be rendered as a standalone page.
    permalink:      /people/:title/index.html  # Defines the URL structure for individual profile pages.
    # Example URL: /people/john-doe/ will render as /people/john-doe/index.html


# -------------------------------------------------
# Navigation Bar Settings
# -------------------------------------------------
nav:
  - name:           "home"
    href:           ""
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "team"
    href:           "/team"


# -------------------------------------------------
# Default Layout Settings for Different Content Types
# -------------------------------------------------
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "people"
    values:
      layout: "profile"